version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/emerald-lattice-358105/my-backend:1.8
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/myfolder/src
    env_file:
      - ./.env
    ports:
      - 3000:3000
